### ISSUE TITLE
Does this method work for sd1.5 or sdxl? Or is it suitable for adding controlnet?

### ISSUE THREAD

**Issue by balala8** [OutofAi/OutofFocus#2]

**Comment by OutofAi** [comment]
The suitability of method (either pivotal tuning or cross-attention replacement) is quite universal when it comes to diffusion models, but the issue is that it won't work by just swapping the models in the current code, cause of the number of attention layers being different and especially SDXL require crop and time information for sampling but can be fixed, we might consider adding variety of models depending on popularity of the tool

**Comment by victorca25** [comment]
Would be very interesting to consider SD1.5 if possible and try it out with lower-end hardware, since the current requirements are inaccessible for most people

**Comment by balala8** [comment]
> The suitability of method (either pivotal tuning or cross-attention replacement) is quite universal when it comes to diffusion models, but the issue is that it won't work by just swapping the models in the current code, cause of the number of attention layers being different and especially SDXL require crop and time information for sampling but can be fixed, we might consider adding variety of models depending on popularity of the tool

I understand. Thank you.

**Comment by OutofAi** [comment]
> Would be very interesting to consider SD1.5 if possible and try it out with lower-end hardware, since the current requirements are inaccessible for most people

You can replace the model with SD1.5, the examples won't work, but the rest should work, at least in my test did, but you don't get the memory reduction, I think, you looking for, due to the size of the negative prompts that are getting optimised and I think the size of the unet being the same in both models, it should be exactly the same
